#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "Chrome"
category = "浏览器"
author = ["Cno"]
url = "https://portableapps.com/apps/internet/google_chrome_portable"
description = "Chrome，不一样的浏览器体验"
tags = ["chromium"]
language = "Multi"
scope = "Google"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "External"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "Chrome/GoogleChromePortable.exe"]
# build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]


# 额外备注
[extra]
require_windows = true
# missing_version = ""
