#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "优酷"
category = "影音播放"
author = ["Cno <cno4tech@gmail.com>"]
url = "https://youku.com/product/index"
description = "为好内容全力以赴"
tags = ["流媒体", "正版"]
language = "zh-CN"
scope = "Youku"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/YOUKU.exe"]
# build_cover = ""
# build_delete = ["$APPDATA","$PLUGINSDIR"]

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "优酷"
sourceFile = "YOUKU.exe"
recursiveUnzipList = ["$PLUGINSDIR", "app-32.7z"]

# 额外备注
[extra]
# require_windows = false
# missing_version = ""
weekly = true
