# 任务基本信息
[task]
name = "TrafficMonitor"
category = "实用工具"
author = ["undefined"]
url = "https://github.com/zhongyang219/TrafficMonitor"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '_x64.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}/TrafficMonitor/TrafficMonitor.exe"]
build_cover = "cover"
#build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName="TrafficMonitor"
sourceFile  = "TrafficMonitor/TrafficMonitor.exe"
recursiveUnzipList = []

# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
