# 任务基本信息
[task]
name = "FirefoxNightly"
category = "浏览器"
author = "undefined"
url = "http://scoop.sh/FirefoxNightly"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
scoopManifestName = "firefox-nightly"
bucketName = "Versions"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "FirefoxNightly"
sourceFile = "firefox.exe"
recursiveUnzipList = [ "core" ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
