# 任务基本信息
[task]
name = "adb"
category = "开发辅助"
scope = "Google"
author = ["Cno"]
url = "https://developer.android.com/studio/releases/platform-tools"
description = "Android Debug Bridge"
tags = ["Android","debug"]
language = "en-US"

# 指定使用的模板
[template]
scraper = "Redirection_Parse"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/adb.exe"]
build_cover = "cover"
# build_delete = []
revised_version = false

# 爬虫模板临时参数
[scraper_temp]
redirection_url = "https://dl.google.com/android/repository/platform-tools-latest-windows.zip"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "adb"
sourceFile = "adb.exe"
recursiveUnzipList = ["platform-tools"]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
