#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "adb"
category = "开发辅助"
scope = "Google"
author = ["Cno <cno4tech@gmail.com>"]
url = "https://developer.android.com/tools/releases/platform-tools"
description = "Android Debug Bridge"
tags = ["Android", "debug"]
language = "en-US"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
download_link = 'https:\/\/dl\.google\.com\/android\/repository\/platform-tools-latest-windows\.zip'
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/adb.exe"]
build_cover = "cover"
# build_delete = []
# main_program = false

# 爬虫模板临时参数
[scraper_temp]
version_selector = "h4"
ua = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "adb"
sourceFile = "adb.exe"
recursiveUnzipList = ["platform-tools"]


# 额外备注
[extra]
# require_windows = false
# missing_version = ""
weekly = true
