# 任务基本信息
[task]
name = "AndroidStudio"
category = "集成开发"
author = "JohnsonRan"
url = "https://scoop.sh/android-studio-canary"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
scoopManifestName = "android-studio-canary"
bucketName = "Versions"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "AndroidStudio"
sourceFile = 'bin\studio64.exe'
recursiveUnzipList = ['android-studio']



# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
