#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "AndroidStudio"
category = "集成开发"
author = ["undefined"]
scope = "scoop"
url = "https://github.com/ScoopInstaller/Extras/blob/master/bucket/android-studio.json"
description = "The official Integrated Development Environment (IDE) for Android app development"
tags = ["android", "java", "kotlin"]
language = "en-US"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}"]
# build_cover = ""
# build_delete = []
main_program = false

# 爬虫模板临时参数
[scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "AndroidStudio"
sourceFile = "android-studio\\bin\\studio64.exe"
recursiveUnzipList = []


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
