#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "AnyDesk"
category = "远程连接"
author = ["Cno <cno4tech@gmail.com>"]
url = "https://anydesk.com"
description = "快速远程桌面应用程序"
tags = []
language = "Multi"
scope = "Anydesk"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Click2Install"

# 使用到的正则
[regex]
download_link = 'https:\/\/download\.anydesk\.com\/AnyDesk\.exe'
download_name = '\.exe'
# scraper_version = '"id":"win_exe","version":"[0-9.]+"'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 1
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 自动制作模板要求的参数
[producer_required]
shortcutName = "AnyDesk"

# 爬虫模板临时参数
[scraper_temp]
version_page_url = "https://anydesk.com/en/downloads"
version_selector = ".d-block"
# download_page_url = "https://anydesk.com/zhs/downloads/thank-you?dv=win_exe"
# download_selector = "#download-button"

# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
