#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "阿里云盘"
category = "下载上传"
author = "Cno"
url = "https://yunpan.aliyun.com/"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/aDrive.exe"]
# build_cover = ""
build_delete = ["$PLUGINSDIR", "$TEMP"]

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "阿里云盘"
sourceFile = "aDrive.exe"
recursiveUnzipList = []


# 额外备注
[extra]
# require_windows = false
# missing_version = "${taskName}/aDrive.exe"
