#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "curl"
category = "下载上传"
author = "undefined"
url = "https://github.com/ScoopInstaller/Main/blob/master/bucket/curl.json"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.tar\.xz'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "${taskName}"
sourceFile = "curl.exe"
recursiveUnzipList = ['/curl-\S+-win64-mingw\.tar/','/curl-\S+-win64-mingw/','bin']
noDesktop = true
addPath = true

# 额外备注
# [extra]
# require_windows = false
# missing_version = ""