#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "balenaEtcher"
category = "压缩镜像"
author = "Hydrogen"
url = "https://github.com/balena-io/etcher"

# 指定使用的模板
[template]
# scraper = "External"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ""
download_name = 'balenaEtcher-Portable-[\d\.]+.exe'
# scraper_version = ""

# 通用参数
[parameter]
# resolver_cd = ["",""]
# compress_level = 1
build_manifest = ["${taskName}.wcs", "${taskName}/balenaEtcher.exe"]
# build_cover = "cover.7z"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "balenaEtcher"
sourceFile = "balenaEtcher.exe"
recursiveUnzipList = ["$PLUGINSDIR", "app-64.7z"]

# 额外备注
[extra]
# require_windows = false
# missing_version = false
