# 任务基本信息
[task]
name = "酷我音乐"
category = "影音播放"
author = ["Cno"]
url = "https://www.kuwo.cn/down"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
#download_link = ""
download_name = '\.exe'
#scraper_version = ""

# 通用参数
[parameter]
# resolver_cd = ["",""]
#compress_level = 1
build_manifest = ['workflows/setup.toml', '${taskName}/KwMusic.exe']
#build_cover = "cover.zip"
build_delete = ["$WINDIR", "$TEMP", "$PLUGINSDIR", "$APPDATA", "readme.txt", "Uninstall.exe", "Uninstall.exe.nsis"]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "酷我音乐"
sourceFile = "KwMusic.exe"
recursiveUnzipList = []

# 额外备注
[extra]
# require_windows = false
missing_version = "${taskName}/KwMusic.exe"
