# 任务基本信息
[task]
name = "scrcpy"
category = "实用工具"
author = "undefined"
url = "https://github.com/Genymobile/scrcpy"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'win64-v.*\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "scrcpy"
sourceFile = "scrcpy.exe"
recursiveUnzipList = [ '/scrcpy-win64-v[\d\.]+/' ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
