# 任务基本信息
[task]
name = "NeatDownloadManager"
category = "下载上传"
author = ["undefined"]
url = "https://www.neatdownloadmanager.com/index.php/en/"
description = "Neat Download Manager is a free Internet Download Manager"
tags = []
language = "en-US"
scope = "NeatDownloadManager"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Click2Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "NeatDownloadManager"


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
