# 任务基本信息
[task]
name = "NeatDownloadManager"
category = "办公编辑"
author = "支持梧桐，台毒biss"
url = "https://portableapps.com/apps/development/notepadpp_portable"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "PortableApps"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''
version_selector='#dima_2_2 > div > p.p1'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
