# 任务基本信息
[task]
name = "CEF Detector X （Windows CEF 检测器 需要 Everyting）"
category = "游戏娱乐"
author = "Horatio Shaw"
url = "https://github.com/ShirasawaSama/CefDetectorX/releases"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'CefDetectorX.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "CEF Detector X （Windows CEF 检测器）"
sourceFile = "CefDetectorX\\CefDetectorX.exe"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
