DATABASE_UPDATE = true
DATABASE_PATH = "./database.json"

REMOTE_ENABLE = false
REMOTE_NAME = "pineapple"
REMOTE_PATH = "/hdisk/edgeless/插件包"

DIR_TASKS = "./tasks"
DIR_WORKSHOP = "./workshop"
DIR_BUILDS = "./builds"

MAX_BUILDS = 1
MAX_RETRY_SCRAPER = 3
MAX_RETRY_RESOLVER = 3

ARIA2_SPAWN = true
ARIA2_PORT = 16800
#ARIA2_SECRET = "edgeless"
ARIA2_THREAD = 4
# GLOBAL_PROXY = "http://localhost:8888"
