# 任务基本信息
[task]
name = "Smap"
category = "实用工具"
author = ["undefined"]
url = "https://github.com/s0md3v/Smap"
description = "passive Nmap like scanner built with shodan.io"
tags = ["nmap"]
language = "Multi"
scope = "github"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "External"

# 使用到的正则
[regex]
# download_link = ''
download_name = '_amd64.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}/smap.exe"]
# build_cover = ""
# build_delete = []
main_program = false

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
