#:schema ../../schema/task.json
# 任务基本信息
[task]
author = ${ task.author }
name = "${ task.name }"
scope = "${ task.scope }"
category = "${ task.category }"
url = "${ task.url }"
description = "${ task.description }"
language = "${ task.language }"
# flags = ""

# 指定使用的模板
[template]
${ template.scraper }
# resolver = ""
producer = "${ template.producer }"

# 使用到的正则
[regex]
# download_link = ''
download_name = '${ regex.download_name }'
# scraper_version = ''

# 通用参数
[parameter]
build_manifest = ${ parameter.build_manifest }
# resolver_cd = []
# compress_level = 5
# build_cover = ""
# build_delete = []
# revised_version = false
# main_program = false

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
${ producer_required }

# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true

# 对 package.toml 的补丁
# [package_patch]
