# 任务基本信息
[task]
name = "${task.name}"
category = "${task.category}"
author = "${task.author}"
url = "${task.url}"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "${template.producer}"

# 使用到的正则
[regex]
#download_link = ""
download_name = "${regex.download_name}"
#scraper_version = ""

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 1
build_manifest = [${parameter.build_manifest}]
# build_cover = ""
# build_delete = []

# 自动制作模板要求的参数
[producer_required]
${producer_required}

# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
