# 任务基本信息
[task]
name = "YesPlayMusic"
category = "影音播放"
author = ["Cno"]
url = "https://github.com/qier222/YesPlayMusic"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'Setup.*\.exe$'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/YesPlayMusic.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "YesPlayMusic"
sourceFile = "YesPlayMusic.exe"
recursiveUnzipList = ["$PLUGINSDIR", "app-64.7z"]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
