# 任务基本信息
[task]
name = "分区助手"
category = "磁盘数据"
author = ["Cno"]
scope = "Aomei"
url = "https://www.disktool.cn/download.html"
description = "无损分区、分区扩容、系统迁移"
tags = ["partition"]
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.7z'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}/PartAssist.exe"]
# build_cover = ""
# build_delete = []
main_program = "PartAssist.exe"

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "分区助手"
sourceFile = "StartPartAssist.exe"
recursiveUnzipList = [ "PAWinPEx64" ]


# 额外备注
[extra]
# require_windows = false
missing_version = "${taskName}/PartAssist.exe"
