# 任务基本信息
[task]
name = "Wireshark"
category = "开发辅助"
author = ["undefined"]
url = "https://www.wireshark.org/download.html"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "PortableApps"

# 使用到的正则
[regex]
download_link = 'https?:\/\/[\w/.]+WiresharkPortable64_[0-9.]+\.paf\.exe'
download_name = '\.exe'
scraper_version = 'Stable Release\s*\([0-9.]+\)'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
version_selector = ".accordion-toggle"


# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
