# 任务基本信息
[task]
name = "腾讯会议"
category = "网课会议"
author = "Cno"
url = "https://meeting.tencent.com/download-center.html"

# 指定使用的模板
[template]
scraper = "REST_API"
# resolver = ""
producer = "External"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/wemeetapp.exe"]
build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
download_path = "info-list.0.url"
version_path = "info-list.0.version"
api_url = "https://meeting.tencent.com/web-service/query-download-info?q=[{%22package-type%22:%22app%22,%22channel%22:%220300000000%22,%22platform%22:%22windows%22}]&c_os=web&c_os_version=1&c_os_model=web&c_timestamp=1650264596931&c_instance_id=5&c_nonce=fyFysGZB&c_app_id=1400143280&c_app_version=1&c_lang=zh-cn&c_district=0&nonce=RrTkRs8rDjcYBsDT"

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
