# 任务基本信息
[task]
name = "win-vind"
category = "实用工具"
author = ["undefined"]
url = "https://github.com/pit-ray/win-vind"
description = "You can operate Windows with key bindings like Vim."
tags = ["vim"]
language = "en-US"
scope = "github"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '64bit_portable\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "win-vind"
sourceFile = "win-vind.exe"
recursiveUnzipList = [ "win-vind" ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
