#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "ToDesk"
category = "远程连接"
author = "Cno"
url = "https://www.todesk.com/download.html"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}\\ToDesk.exe"]
# build_cover = ""
build_delete = ["$PLUGINSDIR"]

# 爬虫模板临时参数
[scraper_temp]
version_selector = '#__layout > div > div.tddownload.wrap > div.tcont_bx > div.tab_content.tab_content0 > div.left_info.win > section'
download_selector = '#__layout > div > div.tddownload.wrap > div.tcont_bx > div.tab_content.tab_content0 > div.left_info.win > section > div.win_download'

# 自动制作模板要求的参数
[producer_required]
shortcutName = "ToDesk"
sourceFile = "ToDesk.exe"
recursiveUnzipList = []


# 额外备注
# [extra]
require_windows = true
# missing_version = ""
# weekly = true
