# 任务基本信息
[task]
name = "ToDesk"
category = "远程连接"
author = "Cno"
url = "https://www.todesk.com/download.html"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
download_link = '(https?:)*\/?\/.+ToDesk_[\d\.]+\.exe'
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/ToDesk.exe"]
build_cover = "cover"
build_delete = ["$PLUGINSDIR", "uninst.exe"]

# 爬虫模板临时参数
[scraper_temp]
version_page_url = "https://update.todesk.com/windows/uplog.html"
version_selector = ".text"
download_page_url = "https://www.todesk.com/js/common.js"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "ToDesk"
sourceFile = "ToDesk.exe"
recursiveUnzipList = []


# 额外备注
[extra]
# require_windows = false
# missing_version = ""
weekly = true
