# 任务基本信息
[task]
name = "星愿浏览器"
category = "浏览器"
author = "Cno"
url = "https://www.twinkstar.com/"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}/twinkstar.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
download_selector = ".downloadBox"
version_selector = ".downloadBox"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "星愿浏览器"
sourceFile = "twinkstar.exe"
recursiveUnzipList = [ "$PLUGINSDIR", "tw_data" ]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
