#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "星穹铁道跃迁记录导出工具"
category = "游戏娱乐"
author = "Horatio Shaw"
url = "https://github.com/biuuu/star-rail-warp-export"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "崩坏：星穹铁道跃迁记录导出工具"
sourceFile = "StarRailWarpExport.exe"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
