# 任务基本信息
[task]
name = "Nali"
category = "实用工具"
author = ["undefined"]
scope = "scoop"
url = "https://github.com/ScoopInstaller/Main/blob/master/bucket/nali.json"
description = "一个查询IP地理信息和CDN服务提供商的离线终端工具"
tags = ["ip","cdn","ipv6"]
language = "Multi"
lincence = "MIT"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}"]
build_cover = "cover"
# build_delete = []
revised_version = false

# 爬虫模板临时参数
[scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "nali"
sourceFile = "nali-windows-amd64.exe"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
