# 任务基本信息
[task]
name = "360压缩"
category = "压缩镜像"
author = ["Cno"]
scope = "360"
url = "https://yasuo.360.cn/"
description = "压缩解压一键处理，助力办公安全省时"
tags = ["zip","7z"]
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
main_program = "${ProgramFiles_X86}/360/360zip/360zip.exe"

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/360/360zip/Uninstaller.exe"

# 额外备注
[extra]
# require_windows = true
missing_version = "${taskName}/${downloadedFile}"
# weekly = true
