# 任务基本信息
[task]
name = "360压缩"
category = "压缩镜像"
author = ["Cno"]
url = "https://yasuo.360.cn/"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
version_selector = ".ver"
download_selector = ".header__actions"

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
