# 任务基本信息
[task]
name = "Ueli"
category = "实用工具"
author = ["Cno"]
url = "https://github.com/oliverschwendener/ueli"
description = "Keystroke launcher for Windows and macOS"
tags = ["搜索"]
language = "Multi"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '^ueli-[\d\.]*-win\.zip$'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}/ueli.exe"]
# build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "Ueli"
sourceFile = "ueli.exe"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
