# 任务基本信息
[task]
name = "RustDesk"
category = "远程连接"
author = ["Cno"]
url = "https://github.com/rustdesk/rustdesk"
description = "远程桌面软件，开箱即用，无需任何配置。"
tags = []
language = "Multi"
scope = "RustDesk"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Click2Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'rustdesk-[\d\.]+-x86_64.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "RustDesk"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
