# 任务基本信息
[task]
name = "RustDesk"
category = "远程连接"
author = "Cno"
url = "https://github.com/rustdesk/rustdesk"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'windows_x64-portable\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "RustDesk"
sourceFile = "/rustdesk-[0-9\\.]+\\.exe/"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
