#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "2XClient"
category = "远程连接"
author = ["Cno"]
scope = "PortableApps"
url = "https://portableapps.com/apps/utilities/2x_client_portable"
description = "remote server and RDP access client"
tags = ["remote", "rdp"]
language = "Multi"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "PortableApps"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.paf\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/2XClient.exe"]
build_cover = "cover"
# build_delete = ["$PLUGINSDIR","help.html","Other"]

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
