# 任务基本信息
[task]
name = "Motrix"
category = "下载上传"
author = ["undefined"]
url = "https://github.com/agalwood/Motrix"
description = "A full-featured download manager."
tags = []
language = "Multi"
scope = "github"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'Motrix-[0-9.]+-win.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/Motrix.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "Motrix"
sourceFile = "Motrix.exe"
recursiveUnzipList = []


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
