# 任务基本信息
[task]
name = "夸克网盘"
category = "下载上传"
author = ["Cno"]
scope = "alibaba"
url = "https://pan.quark.cn/"
description = "你的高效伴侣"
tags = ["net disk"]
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "REST_API"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
download_path = "data.winInstallerUrl"
version_path = "data.version"
api_url = "https://pan.quark.cn/api/client_version"

# 自动制作模板要求的参数
[producer_required]
argument = "/sp- /silent /norestart /currentuser"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
