# 任务基本信息
[task]
name = "夸克网盘"
category = "下载上传"
author = "Cno"
url = "https://pan.quark.cn/"

# 指定使用的模板
[template]
scraper = "REST_API"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/夸克网盘.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
download_path = "data.winInstallerUrl"
version_path = "data.version"
api_url = "https://pan.quark.cn/api/client_version"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "夸克网盘"
sourceFile = "夸克网盘.exe"
recursiveUnzipList = ["$PLUGINSDIR", "app-64.7z"]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
