#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "MobaXterm"
category = "远程连接"
author = "xrgzs"
url = "https://mobaxterm.mobatek.net/download-home-edition.html"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
download_link = '\/\/download\.mobatek\.net\/\d+\/MobaXterm_Portable_v\d.+\.zip'
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
ua = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0"
version_selector = "[class*='bleu']"
download_selector = "[class*='bleu']"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "MobaXterm"
sourceFile = "/MobaXterm(.+).exe/"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
