#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "Bandizip"
category = "压缩镜像"
author = "Cno"
url = "https://www.bandisoft.com/bandizip/"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
download_link = '\/bandizip\/dl\.php\?web'
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
version_page_url = "https://www.bandisoft.com/bandizip/history/"
version_selector = "body > div.main_content > section > div > div:nth-child(4) > div.cell1"
download_selector = "#bandizip_main > div > a:nth-child(3)"

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
