#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "Bandizip"
category = "压缩镜像"
author = ["Cno <cno4tech@gmail.com>"]
url = "https://www.bandisoft.com/bandizip/"
description = "Bandizip 是一个强大的多功能压缩文件管理工具，可提供很快的解压缩速度和其他各种实用功能。 这是一个免费的软件，其付费版本更是可以使用更多的实用功能。"
tags = ["zip"]
language = "Multi"
scope = "Bandisoft"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
download_link = '\/bandizip\/dl\.php\?web'
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
main_program = "${ProgramFiles_X64}/Bandizip/Bandizip.exe"

# 爬虫模板临时参数
[scraper_temp]
version_selector = ".button"
download_selector = "center"

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X64}/Bandizip/Uninstall.exe"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
