[register]
name = "Register Ext"
step = "Execute"
command = "PotPlayerPortable.exe /RegisterAll"

[link]
name = "Create Shortcut"
step = "Link"
source_file = "PotPlayerPortable.exe"
target_name = "PotPlayer"