[task]
name = "ChromeDriver"
category = "开发辅助"
author = ["undefined"]
scope = "scoop"
url = "https://github.com/ScoopInstaller/Main/blob/master/bucket/chromedriver.json"
description = "An open source tool for automated testing of webapps across many browsers"
tags = ["e2e test","automated"]
language = "Multi"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}"]
build_cover = "cover"
build_delete = ["ChromeDriver/LICENSE.chromedriver"]

# 爬虫模板临时参数
[scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "${taskName}"
sourceFile = "chromedriver.exe"
recursiveUnzipList = []


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
