# 任务基本信息
[task]
name = "Listen1"
category = "影音播放"
author = "undefined"
url = "https://github.com/listen1/listen1_desktop"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'listen1_[0-9.]+_win_x64.7z'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/Listen1.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "Listen1"
sourceFile = "Listen1.exe"
recursiveUnzipList = []


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
