# 任务基本信息
[task]
name = "DreamScene2"
category = "美化增强"
author = ["undefined"]
url = "https://github.com/he55/DreamScene2"
description = "一个小而快并且功能强大的 Windows 动态桌面软件"
tags = ["桌面","壁纸","动态壁纸"]
language = "zh-CN"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'net4\w+\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "DreamScene2"
sourceFile = "DreamScene2.exe"
recursiveUnzipList = ["/net/"]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
