# 任务基本信息
[task]
name = "DreamScene2"
category = "美化增强"
author = ["undefined"]
url = "https://github.com/he55/DreamScene2/releases"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "External"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "DreamScene2"
sourceFile = "${download_name}/DreamScene2.exe"
recursiveUnzipList = []


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
