#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "火绒安全"
category = "安全急救"
author = "Cno"
url = "https://www.huorong.cn"

# 指定使用的模板
[template]
scraper = "Redirection_Parse"
# resolver = ""
producer = "Click2Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
scraper_version = '\d\.\d\.\d\.\d'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
redirection_url = "https://www.huorong.cn/product/downloadHr60.php?pro=hr60&plat=x64UrlAll"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "火绒安全"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
