# 任务基本信息
[task]
name = "火绒安全"
category = "安全急救"
author = "Cno"
url = "https://www.huorong.cn"

# 指定使用的模板
[template]
scraper = "External_Scraper"
# resolver = ""
producer = "Click2Install"

# 使用到的正则
[regex]
download_link = ""
download_name = ""
scraper_version = ""

# 通用参数
[parameter]
# resolver_cd = ["",""]
compress_level = 1
# build_manifest = [""]
# build_cover = "cover.7z"

# 自动制作模板要求的参数
[producer_required]

# 额外备注
[extra]
# require_windows = false
# missing_version = false
