#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "火绒安全"
category = "安全急救"
author = ["Cno <cno4tech@gmail.com>"]
scope = "Huorong"
url = "https://www.huorong.cn"
description = "聚焦专业技术  专注终端安全"
tags = ["safe"]
language = "Multi"

# 指定使用的模板
[template]
scraper = "Redirection_Parse"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
scraper_version = '\d\.\d\.\d\.\d'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
build_cover = "cover"
# build_delete = []
registry_entry = "HuorongSysdiag"

# 爬虫模板临时参数
[scraper_temp]
redirection_url = "https://www.huorong.cn/product/downloadHr60.php?pro=hr60&plat=x64UrlAll"

# 自动制作模板要求的参数
[producer_required]
argument = ""
uninstallCmd = "${ProgramFiles_X64}/Huorong/Sysdiag/uninst.exe"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
