# 任务基本信息
[task]
name = "360安全卫士极速版"
category = "安全急救"
author = ["Cno"]
scope = "360"
url = "https://weishi.360.cn/jisu"
description = "轻松出发，开启安全护航"
tags = ["safe"]
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
main_program = "${ProgramFiles_X86}/360/360Safe/360Safe.exe"

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/360/360Safe/uninst.exe"


# 额外备注
[extra]
# require_windows = false
missing_version = "${taskName}/${downloadedFile}"
