#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "MediaInfo"
category = "媒体处理"
author = "wdw1007"
url = "https://mediaarea.net/en/MediaInfo/Download/Windows"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'MediaInfo_GUI_[0-9,.]{1,}_Windows_x64_WithoutInstaller\.7z'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 1
build_manifest = ["${taskName}.wcs","${taskName}"]
build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
# version_page_url = "https://mediaarea.net/en/MediaInfo/Download/Windows"
# download_page_url = "https://mediaarea.net/en/MediaInfo/Download/Windows"
version_selector = ".download > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(4) > a:nth-child(1)"
download_selector = ".download > tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(3) > small:nth-child(2) > a:nth-child(1)"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "MediaInfo"
sourceFile = "MediaInfo.exe"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
