# 任务基本信息
[task]
name = "百度网盘"
category = "下载上传"
author = ["Cno"]
url = "https://pan.baidu.com/download"

# 指定使用的模板
[template]
scraper = "REST_API"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}/BaiduNetdisk.exe"]
# build_cover = "cover"
build_delete = ["$PLUGINSDIR", "$TEMP"]

# 爬虫模板临时参数
[scraper_temp]
api_url = "https://pan.baidu.com/disk/cmsdata?do=client&t=1639412910616&channel=chunlei&clienttype=0&web=1&logid=MTYzOTQxMjkxMDYwOTAuNDgwODU1ODUxNTczMzEwOA=="
version_path = "guanjia.version"
download_path = "guanjia.url"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "百度网盘"
sourceFile = "BaiduNetdisk.exe"
recursiveUnzipList = [ ]


# 额外备注
[extra]
# require_windows = false
# missing_version = ""
weekly = true