# 任务基本信息
[task]
name = "搜狗五笔"
category = "输入法"
author = ["Cno"]
url = "https://wubi.sogou.com/"
description = "畅快表达"
tags = []
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
download_selector = "#bannerCon_new"
version_selector = "#bannerCon_new"

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
