# 任务基本信息
[task]
name = "腾讯视频"
category = "影音播放"
author = ["Cno"]
url = "https://v.qq.com/download.html"
description = "不负好时光"
tags = ["流媒体","正版"]
language = "zh-CN"
scope = "Tencent"

# 指定使用的模板
[template]
scraper = "Redirection_Parse"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
redirection_url = "https://node.video.qq.com/x/api/download_pc"

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/Tencent/QQLive/QQLiveUninstaller.exe"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
