#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "PotPlayer"
category = "影音播放"
author = ["Cno <cno4tech@gmail.com>"]
scope = "PortableApps"
url = "https://portableapps.com/apps/music_video/potplayer-portable"
description = "hardware enhanced media player"
tags = []
language = "Multi"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "PortableApps"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}"]
# build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
