#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "CrystalDiskMark Aoi Edition"
category = "配置检测"
author = "xrgzs"
url = "https://github.com/chawyehsu/dorado/blob/master/bucket/crystaldiskmark-aoi-edition.json"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}/DiskMark64A.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "CrystalDiskMark Aoi Edition"
sourceFile = "DiskMark64A.exe"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
