#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "TIM"
category = "即时通讯"
author = ["Cno <cno4tech@gmail.com>"]
url = "https://tim.qq.com/download.html"
description = "专注团队沟通协作"
tags = ["qq"]
language = "zh-CN"
scope = "Tencent"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
scraper_version = '"pcVersion":"\d+.\d+(.\d+)*"'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
main_program = "${ProgramFiles_X86}/Tencent/TIM/Bin/QQScLauncher.exe"

# 爬虫模板临时参数
[scraper_temp]
version_page_url = "https://im.qq.com/rainbow/TIMDownload/"
download_page_url = "https://im.qq.com/rainbow/TIMDownload/"

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/Tencent/TIM/TIMUninst.exe"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
