#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "uTools"
category = "实用工具"
author = ["Cno <cno4tech@gmail.com>"]
url = "https://www.u.tools/"
description = "新一代效率工具平台"
tags = ["搜索"]
language = "Multi"
scope = "Utools"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
scraper_version = 'uTools v[0-9]+\.[0-9]+\.[0-9]+'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/uTools.exe"]
# build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
download_page_url = "https://www.u.tools/download/"
download_selector = "div[class^='Dl_dlItems__']"
version_page_url = "https://www.u.tools/docs/guide/changelog.html"
# version_selector = "h2"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "uTools"
sourceFile = "uTools.exe"
recursiveUnzipList = ["$PLUGINSDIR", "app-64.7z"]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
