#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "希沃白板5"
category = "网课会议"
author = "xrgzs"
url = "https://easinote.seewo.com/"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}\\Main\\EasiNote.exe"]
build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
# download_path = "data.downloadUrl"
# version_path = "data.softVersion"
# api_url = "https://e.seewo.com/download/fromSeewoEdu?code=EasiNote5"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "希沃白板5"
sourceFile = "Main\\EasiNote.exe"
recursiveUnzipList = ['/EasiNote5_\d+.\d+.\d+.\d+/']


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
