#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "百度拼音"
category = "输入法"
author = ["Cno <cno4tech@gmail.com>"]
scope = "Baidu"
url = "https://shurufa.baidu.com/"
description = "让世界更懂你"
tags = ["pinyin", "wubi", "hand input", "speech input"]
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
main_program = "${ProgramFiles_X86}/Baidu/BaiduPinyin/${latestVersion}/imeconfig.exe"

# 爬虫模板临时参数
[scraper_temp]
download_selector = "div.downloadBtn"
version_selector = "div.downloadBtn"

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/Baidu/BaiduPinyin/${latestVersion}/Uninst.exe"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
