#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "123云盘"
category = "下载上传"
author = "xrgzs"
url = "https://www.123pan.com/"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}/123pan.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "123云盘"
sourceFile = "123pan.exe"
recursiveUnzipList = [ 'app.7z' ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
