# 任务基本信息
[task]
name = "Icalingua++"
category = "即时通讯"
author = "Horatio Shaw"
url = "https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/releases"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\x64.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
