# 任务基本信息
[task]
name = "网易云音乐"
category = "影音播放"
author = ["Cno"]
url = "https://music.163.com/#/download"
description = "音乐的力量"
tags = ["流媒体","正版"]
language = "zh-CN"
scope = "netease"

# 指定使用的模板
[template]
scraper = "Redirection_Parse"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = ["$PLUGINSDIR"]

# 爬虫模板临时参数
[scraper_temp]
redirection_url = "https://music.163.com/api/pc/package/download/latest"

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/NetEase/CloudMusic/UnInstall.exe"



# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
