# 任务基本信息
[task]
name = "IntelliJ IDEA"
category = "集成开发"
author = ["JohnsonRan"]
url = "https://github.com/ScoopInstaller/Extras/blob/master/bucket/idea.json"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]


# 自动制作模板要求的参数
[producer_required]
shortcutName = "IntelliJ IDEA"
sourceFile = 'bin\idea64.exe'
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
