#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "360极速浏览器X"
category = "浏览器"
author = "Cno"
url = "https://browser.360.cn/eex/index.html"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}/360chromex.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
version_selector = ".main-box"
download_selector = ".main-box"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "360极速浏览器X"
sourceFile = "360chromex.exe"
recursiveUnzipList = [ "chrome.7z", "Chrome-bin" ]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
