#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "FastCopy"
category = "资源管理"
author = ["Cno <cno4tech@gmail.com>"]
url = "https://fastcopy.jp/"
description = "fast file copier and remover"
tags = []
language = "Multi"
scope = "FastCopy"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ""
download_name = "/.exe/"
# scraper_version = ""

# 通用参数
[parameter]
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
build_delete = []
main_program = "${Home}/FastCopy/setup.exe"
# registry_entry = "FastCopy"

# 爬虫模板临时参数
[scraper_temp]
version_selector = ".main_head1_main"
download_selector = ".dl_link:eq(1)"


# 自动制作模板要求的参数
[producer_required]
argument = "/SILENT"
uninstallCmd = "${Home}/FastCopy/setup.exe /r /SILENT"

# 额外备注
[extra]
# require_windows = false
# missing_version = ""
weekly = true
