#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "FastCopy"
category = "资源管理"
author = "Cno"
url = "https://fastcopy.jp/"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ""
download_name = "/.exe/"
# scraper_version = ".main_head1_main"

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 1
build_manifest = ["${taskName}.wcs", "${taskName}/${downloadedFile}"]
# build_cover = ""
build_delete = []

# 爬虫模板临时参数
[scraper_temp]
version_selector = ".main_head1_main"
download_selector = ".dl_link:eq(1)"


# 自动制作模板要求的参数
[producer_required]
argument = "/SILENT"


# 额外备注
[extra]
# require_windows = true
# missing_version = ""
weekly = true
