# 任务基本信息
[task]
name = "bottom"
category = "实用工具"
author = ["undefined"]
url = "https://github.com/ClementTsang/bottom"
description = "Yet another cross-platform graphical process/system monitor."
tags = []
language = "en-US"
scope = "github"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '-pc-windows-msvc\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}"]
build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "bottom"
sourceFile = "btm.exe"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
