# 任务基本信息
[task]
name = "搜狗拼音"
category = "输入法"
author = ["Cno"]
url = "https://pinyin.sogou.com/"
description = "万物输入皆搜狗"
tags = []
language = "zh-CN"
scope = "Sogou"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
correct_version = "${downloadedFile}"
main_program = "${ProgramFiles_X86}/SogouInput/SogouExe/SogouExe.exe"

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/SogouInput/${correctVersion}/Uninstall/Uninstall.exe"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
