#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "WPS"
category = "办公编辑"
author = "Cno"
url = "https://platform.wps.cn"

# 指定使用的模板
[template]
scraper = "REST_API"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/$EXEFILE"]
build_cover = "cover"
build_delete = ["oeminfo", "oem_enterprise.txt", "oem_static.exe", "oem.ini"]

# 爬虫模板临时参数
[scraper_temp]
api_url = "https://www.wps.cn/platformUrls"
version_path = "productDetail.productVcode"
download_path = "productDetail.productButtonUrl"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "WPS"
sourceFile = "$EXEFILE"
recursiveUnzipList = ["$_11_"]


# 额外备注
[extra]
# require_windows = false
missing_version = "${taskName}/$EXEFILE"
weekly = true