#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "Notepad--"
category = "办公编辑"
author = "undefined"
url = "https://gitee.com/cxasm/notepad--/releases/latest"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
download_link = '\/cxasm\/notepad--\/releases\/download\/v\d+(\.\d+)+\/Notepad--v\d+(\.\d+)+-win10-portable*\.zip'
download_name = 'Notepad--v\d+(\.\d+)+-win10-portable*\.zip'
# scraper_version = ''
# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs","${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
ua = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0"
version_selector = ".icon-tag~ *"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "Notepad--"
sourceFile = "Notepad--.exe"
recursiveUnzipList = ["/Notepad--v\\d+(\\.\\d+)+-win10-portable/" ]


# 额外备注
[extra]
# require_windows = true
# missing_version = ""
# weekly = true
