# 任务基本信息
[task]
name = "驱动总裁"
category = "驱动管理"
author = ["Cno"]
url = "https://www.sysceo.com/Software-softwarei-id-258.html"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
download_selector = "body > div.main > div.contentFrame > div.toolInfo.fl > div > div"
version_selector = "body > div.main > div.contentFrame > div.toolInfo.fl > div > div > div.msg.fl.cl > ol > li:nth-child(2)"

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
