# 任务基本信息
[task]
name = "java-zulu-jdk8-fx"
category = "运行环境"
author = ["wdw1007"]
url = "https://www.azul.com/downloads/"

# 指定使用的模板
[template]
scraper = "REST_API"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 1
build_manifest = ["${taskName}.wcs","${taskName}"]
build_cover = "cover"
# build_delete = []

# 爬虫模板临时参数

[scraper_temp]
api_url = "https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?jdk_version=8&os=windows&arch=x86&hw_bitness=64&ext=zip&bundle_type=jdk&javafx=true&release_status=both"
version_path = "jdk_version"
download_path = "url"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "NUL"
sourceFile = "bin/java.exe"
recursiveUnzipList = ['/zulu[0-9,a-z,.,-]{1,}_x64/']



# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
weekly = true
