# 任务基本信息
[task]
name = "爱奇艺"
category = "影音播放"
author = ["Cno"]
scope = "iqiyi"
url = "https://app.iqiyi.com/pc/player/index.html"
description = "轻快 流畅 正版 超清"
tags = ["streaming media","legal copy"]
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
download_link = 'http.+IQIYIsetup_app\.exe'
download_name = '\.exe'
#scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
version_selector = "#J-download-verTxt"

# 自动制作模板要求的参数
[producer_required]


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
