# 任务基本信息
[task]
name = "哔哩哔哩"
category = "影音播放"
author = ["Cno"]
scope = "bilibili"
url = "https://app.bilibili.com/"
description = "(゜-゜)つロ 干杯~"
tags = ["acg","we media"]
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml","${taskName}/哔哩哔哩.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "哔哩哔哩"
sourceFile = "哔哩哔哩.exe"
recursiveUnzipList = [ "$PLUGINSDIR", "app-64.7z" ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
