#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "QQ"
category = "即时通讯"
author = ["Cno <cno4tech@gmail.com>"]
url = "https://im.qq.com/pcqq/index.shtml"
description = "从心出发·趣无止境"
tags = []
language = "zh-CN"
scope = "Tencent"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
download_link = 'https:\/\/dldir1\.qq\.com\/qqfile\/qq/QQNT\/[\w\/.]+_x64\.exe'
download_name = '\.exe'
scraper_version = '"ntVersion":\s?.+,'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
main_program = "${ProgramFiles_X86}/Tencent/QQ/Bin/QQScLauncher.exe"

# 爬虫模板临时参数
[scraper_temp]
version_page_url = "https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/windowsDownloadUrl.js"
download_page_url = "https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/windowsDownloadUrl.js"

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/Tencent/QQ/QQUninst.exe"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
