#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "QQ"
category = "即时通讯"
author = ["Cno"]
url = "https://im.qq.com/pcqq"
description = "从心出发·趣无止境"
tags = []
language = "zh-CN"
scope = "Tencent"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
download_link = 'https://dldir1.qq.com/qqfile/qq/PCQQ[\w./]+.exe'
download_name = 'QQ${latestVersion}.exe'
scraper_version = 'QQ Windows版 \d+\.\d+(\.\d+)*'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
main_program = "${ProgramFiles_X86}/Tencent/QQ/Bin/QQScLauncher.exe"

# 爬虫模板临时参数
[scraper_temp]
version_selector = ".desc-version"
download_selector = ".btn-downlond"

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/Tencent/QQ/QQUninst.exe"


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
