name: Debug

on:
  pull_request:
    branches:
      - next

jobs:
  serve:
    runs-on: windows-2019
    steps:
      # 获取仓库源码
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.ref }}

      # 缓存yarn
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # 安装依赖
      - name: Install dependencies
        run: yarn
      
      # 以Debug模式运行构建任务
      - name: Run scripts
        run: yarn dev -g