name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  serve:
    runs-on: windows-latest
    steps:
      # 获取仓库源码
      - uses: actions/checkout@v2

      # 获取rclone
      - name: rclone
        run: git clone https://oauth2:$env:TOKEN@github.com/Cnotech/rclone
        shell: pwsh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 取出rclone
      - name: copy rclone
        run: mv .\rclone\* .\

      # 安装依赖
      - name: yarn
        run: yarn
      
      # 构建CPU-Z
      - name: build
        run: yarn serve -t CPU-Z -f
