name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 16 * * *'

jobs:
  serve:
    runs-on: windows-latest
    steps:
      # 获取仓库源码
      - uses: actions/checkout@v2

      # 获取rclone
      - uses: actions/checkout@v2
        with:
          repository: Cnotech/rclone
          token: ${{ secrets.RCLONE_TOKEN }}
          path: rclone

      # 取出rclone
      - name: copy rclone
        run: mv .\rclone\* .\

      # 缓存yarn
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # 安装依赖
      - name: yarn
        run: yarn
      
      # 构建任务
      - name: build
        run: yarn serve -g

      # 回传数据库
      - name: commit database
        run: |
          git config --local user.email "dsyourshy@qq.com"
          git config --local user.name "Actions bot"
          git commit -m "Update database" -a

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
