name: Serve-next

on:
  push:
    branches: [next]
    paths:
      - "src/**"
      - "templates/**"
      - "tasks/**"
      - ".github/**"
  schedule:
    - cron: "0 20 * * *"

jobs:
  serve:
    runs-on: windows-2019
    steps:
      # 获取仓库源码
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.ref }}

      # 获取rclone
      - uses: actions/checkout@v4
        with:
          repository: Cnotech/rclone
          token: ${{ secrets.RCLONE_TOKEN }}
          path: rclone

      # 取出rclone
      - name: Copy rclone
        run: mv .\rclone\* .\ && New-Item -Path "~/.config/cloud189" -ItemType Directory && mv .\config.json ~/.config/cloud189/config.json

      # 缓存 node_modules
      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      # 安装依赖
      - name: Install dependencies
        run: npm install -g pnpm@9 && pnpm install

      # 运行构建任务
      - name: Run scripts
        run: pnpm serve -g -e "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
