name: Serve-next

on:
  push:
    branches: [ next ]
    paths:
      - 'src/**'
      - 'templates/**'
      - 'tasks/**'
      - '.github/**'
  schedule:
    - cron: '0 20 * * *'

jobs:
  serve:
    runs-on: windows-2019
    steps:
      # 获取仓库源码
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.ref }}

      # 获取rclone
      - uses: actions/checkout@v3
        with:
          repository: Cnotech/rclone
          token: ${{ secrets.RCLONE_TOKEN }}
          path: rclone

      # 取出rclone
      - name: Copy rclone
        run: mv .\rclone\* .\

      # 缓存yarn
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # 安装依赖
      - name: Install dependencies
        run: yarn
      
      # 运行构建任务
      - name: Run scripts
        run: yarn serve -g