# 任务基本信息
[task]
name = "VSCode"
category = "集成开发"
author = ["Cno"]
url = "https://code.visualstudio.com/"

# 指定使用的模板
[template]
scraper = "Redirection_Parse"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/Code.exe"]
build_cover = "vscode_cover.7z"
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
redirection_url = "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-archive"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "Visual Studio Code"
sourceFile = "Code.exe"
recursiveUnzipList = []


# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
