# 任务基本信息
[task]
name = "360驱动大师"
category = "驱动管理"
author = ["Cno"]
scope = "360"
url = "https://dm.weishi.360.cn/home.html"
description = "百万级驱动库，最新驱动全程自动安装"
tags = ["driver"]
language = "zh-CN"

# 指定使用的模板
[template]
scraper = "Global_Page_Match"
# resolver = ""
producer = "Silent_Install"

# 使用到的正则
[regex]
# download_link = ''
download_name = '\.exe'
scraper_version = '"version"\s*:\s*"\d+\.\d+\.\d+(\.\d+)?",'

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}/${downloadedFile}"]
# build_cover = ""
# build_delete = []
main_program = "${ProgramFiles_X86}/360/360DrvMgr/360DrvMgr.exe"

# 爬虫模板临时参数
[scraper_temp]
download_selector = "body > div.page > div.main > div > a:nth-child(2)"
#version_selector = "#list > li:nth-child(1) > div > span:nth-child(1)"
version_page_url = "https://weishi.360.cn/qudongdashi/updateData.json?callback=jsonpCallback&_=1688231283156"

# 自动制作模板要求的参数
[producer_required]
uninstallCmd = "${ProgramFiles_X86}/360/360DrvMgr/drv_uninst.exe"

# 额外备注
# [extra]
# require_windows = false
# missing_version = ""
