#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "eSearch"
category = "办公编辑"
author = ["Horatio Shaw"]
url = "https://github.com/xushengfeng/eSearch"
description = "截屏 离线OCR 搜索翻译 以图搜图 贴图 录屏 滚动截屏"
tags = ["OCR", "翻译"]
language = "zh-CN"
scope = "github"

# 指定使用的模板
[template]
# scraper = ""
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'eSearch-[\d\.]+-win32-x64.zip'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["workflows/setup.toml", "${taskName}"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "eSearch"
sourceFile = "e-search.exe"
recursiveUnzipList = []


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
